[package]
name = "delegation-latest-update-abi"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@multiversx.com>"]
edition = "2018"
publish = false

[dependencies.delegation_latest_update]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.45.1"
default-features = false
